version: "3.9"

services:

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=embed_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=superz-es
      - cluster.name=superz-es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data


volumes:
    postgres-data:
    elasticsearch-data:
    redis-data:

